### ISSUE TITLE
Bugged time bar in correspondence games

### ISSUE THREAD

**Issue by Jannik66** [prettierlichess/prettierlichess#1]
Hey I just noticed that the remaining time bar is bugged in games which are correspondence.
For example here:
![Bugged View](https://imgur.com/F4rO0UX.png)

**Comment by noahsemus** [comment]
Will look into this now!

**Comment by noahsemus** [comment]
Fixed in next update 🎉

**Comment by Jannik66** [comment]
It still seems bugged for me. But not in every game..
Maybe it's because we started from a position.

![image](https://user-images.githubusercontent.com/36984337/109613902-1c669c00-7b32-11eb-8b0f-f88de988eb29.png)
This is from this game: https://lichess.org/UjDPFLCbyjHy
Also here: https://lichess.org/l4GyjQ5Zhkto

But here it's perfectly fine:
![image](https://user-images.githubusercontent.com/36984337/109614131-8121f680-7b32-11eb-8bd2-d6b56fb825d8.png)
https://lichess.org/MLuPluSaVR8w

**Comment by noahsemus** [comment]
Thanks for the link, it's showing up on my side too, so I will fix this now.

**Comment by noahsemus** [comment]
Yup, you were right! It was because it was started from a specific position. Fixed in the next update.

**Comment by Jannik66** [comment]
Thank you so much! <3

**Comment by Jannik66** [comment]
Fixed for me!
