### ISSUE TITLE
Pieces are clipped on 8th rank of 3D board

### ISSUE THREAD

**Issue by apuddy** [prettierlichess/prettierlichess#11]
![image](https://user-images.githubusercontent.com/6567378/110390989-c1472300-80b6-11eb-9d23-9496e595614b.png)

Seems to be caused by this style:

```
cg-helper cg-container cg-board {
    overflow: hidden !important;
}
```

**Comment by noahsemus** [comment]
Thanks for the report. 3D boards aren't supported, as we need this hidden overflow in order to maintain the board's border-radius when things like highlighted squares occur on the corners.
