### ISSUE TITLE
Small box

### ISSUE THREAD

**Issue by Ravelfett** [prettierlichess/prettierlichess#110]
in analysis, after changing the variant to anything else than "Standard", the box gets too small, making other variants like Antichess, Atomic, Horde or Racing Kinds unreachable
![image](https://user-images.githubusercontent.com/41432535/184194254-6bc16799-e374-40db-89d5-576fd9a72fc6.png)

I figured doing this somewhat fixed it but I'm no css person so i dont know what im doing
![image](https://user-images.githubusercontent.com/41432535/184194617-a5e76bdc-bb6c-410a-b23d-58bb19d22d13.png)

**Comment by kieferro** [comment]
Yes, that should not be like that. Thank you for the bug report. I will take care of it.
