### ISSUE TITLE
centre home page on quick pairings

### ISSUE THREAD

**Issue by gennaro-tedesco** [prettierlichess/prettierlichess#112]
Thank you for the great extension!

However, I find it puzzling that with `prettierlichess` the home page screens if focus for the most on the "watch game" (with some random game being played) rather than on the quick pairings (like in the normal home screen): is this the best solution? Would it not be possible to add an option so that the user can choose and opt out of this new design? Most users first user input on lichess is just to find a game, not to have their screen visual focussing 80% on some random game being played.

**Comment by kieferro** [comment]
> Thank you for the great extension!

Thank you very much, we are always happy when our extension helps someone :)

I can understand the request, although (at least on the computer) one should also always see the quick pairings on the left and these are thus directly accessible. Sure, to challenge someone you have to scroll down. But by still showing the quick pairings on the left, you don't even have to do more to start a game than with the normal design, or am I missing something?
On the other hand, it is difficult to make something that suits everyone. Some people only come to Lichess to do the puzzle of the day. Others just come to play. You simply can't have everything.

> add an option so that the user can choose and opt out of this new design

Could you be a bit more specific? Would this option then really only refer to the position of the quick pairings or somehow to the whole design? I'd be happy to add options to the extension, but then I'd need to know more specifically what you have in mind.

**Comment by gennaro-tedesco** [comment]
I do see the pairings on the left hand side, I was only wondering whether it is because of some particular settings of my browser/computer or by default.

 > Would this option then really only refer to the position of the quick pairings or somehow to the whole design?

It would only refer to the position of the quick pairings, the rest of the design being untouched: essentially I found it strange to have the screen centered on someone else's game and pairing on the left rather than viceversa (like in the original lichess interface, so to speak).

However, if this has not been raised by other users I understand one cannot just add options for any request, so feel free to close as irrelevant if you deem it the case :)

**Comment by kieferro** [comment]
> I was only wondering whether it is because of some particular settings of my browser/computer or by default.

This should be structured like this by default (example image: https://prettierlichess.github.io/assets/homepageScreenshot.png)

> It would only refer to the position of the quick pairings, the rest of the design being untouched

I'm sorry, but I don't think it's worth adding an extra option for that. I agree that it would make more sense if there was more focus on the quick pairings, but then the design would have to be fundamentally changed. I can't decide that on my own, but would also have to discuss it with the other admins.
I will keep this in mind and see if there is a good solution. But I will close this for the time being.

**Comment by kieferro** [comment]
I tried a bit and this should be much easier than I thought to implement. I was planning to add the option to switch the extension on and off anyway. I can probably implement the suggestion here right away.
In addition, some people in the Chrome Store reviews have remarked that they would like to have such an option.

**Comment by gennaro-tedesco** [comment]
Ah, great, thank you for following up!

**Comment by ivanarsovski** [comment]
Would love to see this implemented, the way it is now is great, but to have something similar to the original layout with the quick pairings on the center, while maintaining the design and main ideas would be ideal for a lot of players!

**Comment by kieferro** [comment]
@ivanarsovski Thanks for the comment, it's good to know that more people would be interested in such a feature.
I'm already working on an implementation of the feature, but it's not easy because it requires a fundamental change in the way the styling is added to the website. It may take a little while before the feature comes. But it is currently the first priority and should be released in the next update if everything goes according to plan.

**Comment by TheHypnotist333** [comment]
I know it doesn't really matter but I definitely prefer it the way it is already. It would be nice to have the option to switch it since some people don't like that. I usually watch the masters play on the home screen. To start a game is right there on the left.

**Comment by kieferro** [comment]
@TheHypnotist333 I'm sorry if that wasn't made clear, but my plan actually is to include that only as an option. The default would stay the same, but there would be the option in the popup to switch the layout.

**Comment by kieferro** [comment]
I have implemented the feature now. We will roll out an update soon. With a version greater than `3.5` you should then be able to choose between different layouts in the popup.
