### ISSUE TITLE
Cannot export profile

### ISSUE THREAD

**Issue by rafaelrcenteio** [prettierlichess/prettierlichess#117]
Trying to export Prettier Lichess profile results in download failure.

Info:
Pretter Lichess 3.5.0
Ubuntu x64 22.04
Firefox 105.0.3 (64-bit)

**Comment by kieferro** [comment]
I am still replicating the setup to see if I have the bug on a similar setup as well. Could you explain a bit more (or feel free to use screenshots) what kind of download failure occurs?

**Comment by rafaelrcenteio** [comment]
Hello. Basically, when one clicks "export profile" , the dialog to save the file opens up. When you hit save, the download fails.

**Comment by kangzhiz** [comment]
I am running into the same bug with the following setup:

Firefox 106.0.5 (64-bit)
macOS 12.6
Prettier Lichess 3.5.0
