### ISSUE TITLE
"Waiting for opponent" text clips into the board in vertical layout

### ISSUE THREAD

**Issue by Kyllingene** [prettierlichess/prettierlichess#118]
On the vertical layout (any zoom level), the "Waiting for opponent" text clips onto the chessboard.

![image](https://user-images.githubusercontent.com/69094702/197415346-5d24e123-b356-4502-88e3-d2701ffbc5fe.png)

**Comment by kieferro** [comment]
Thanks for reporting this bug. I have fixed it in the code here now. We will be releasing a patch for it soon.
