### ISSUE TITLE
Unabled to see the countdown timer for time remaining to play first move

### ISSUE THREAD

**Issue by kangzhiz** [prettierlichess/prettierlichess#120]
When starting a game as white, the countdown timer for my time remaining to play the first move is missing. (After I play my first move, I CAN see the timer for my opponent).
When playing as black, I am able to see the countdown timer for my opponent, but cannot see my own timer when it's my turn to move.

Firefox 106.0.5 (64-bit)
macOS 12.6
Prettier Lichess 3.5.0

**Comment by kieferro** [comment]
Thank you for reporting the bug. It should be fixed now and we will probably roll it out with the 3.6.0 release.
