### ISSUE TITLE
Lichess broadcast page becomes unusable when extension is enabled

### ISSUE THREAD

**Issue by instructionmanual** [prettierlichess/prettierlichess#123]
![image](https://user-images.githubusercontent.com/81769016/202033681-e22a6296-6695-4430-ba4f-3ea1f6d5552d.png)

https://lichess.org/broadcast/meltwater-champions-chess-tour-finals-2022/round-2/8w56GHe5 is where I noticed the issue.

**Comment by kieferro** [comment]
Yes, there were some changes to the lichess frontend in https://github.com/lichess-org/lila/commit/6e3c3ac0233d06b30267578ff2f312603f9ac511. I fixed the issue now and we will release a patch soon.
