### ISSUE TITLE
Feature request: Separate colors on the board and primary color

### ISSUE THREAD

**Issue by Jannik66** [prettierlichess/prettierlichess#13]
Hey, I would love it if the displayed colors on the board were separate from the primary color. My primary color is a little bit hard to see on the board and I don't want to change it :(

**Comment by noahsemus** [comment]
Eventually we could add separate color selectors for board arrows, but this is not too high up on our priorities right now.

**Comment by noahsemus** [comment]
And 20 days later... it's in the next release! Thanks for the suggestion.
