### ISSUE TITLE
Analysis tab proportions are completely messed up

### ISSUE THREAD

**Issue by MuhdRayan10** [prettierlichess/prettierlichess#130]
Hello! I'd just like to report that whilst using Prettier Lichess, which has been a great extension thus far, the proportions of the different widgets of the analysis tab are completely messed up in my case. 

<img width="922" alt="image" src="https://user-images.githubusercontent.com/119870649/209400408-c8cf4985-6bb9-484d-804f-3f3b328893ab.png">

This is how it looks like.

Some relevant info if necessary:
OS: Windows 11 Pro
Browser: Opera GX

It would be nice if you would look into it, I appreciate the good work!

**Comment by kieferro** [comment]
Thank you for reporting this bug. I can replicate this behavior when I change my screen size. I will take care of it and we will release a patch soon.

> I appreciate the good work!

<3

**Comment by MuhdRayan10** [comment]
no problem, glad you’re still maintaining the extension.
