### ISSUE TITLE
Legal moves indicator not displaying on dark squares

### ISSUE THREAD

**Issue by quasicredible** [prettierlichess/prettierlichess#132]
![legal moves wrong](https://user-images.githubusercontent.com/122417379/211699899-9bcd2386-985e-4831-96d7-8a9da0a553e8.png)

Looks like the legal moves/premoves indicators aren't displaying on dark squares. I use Lichess daily and I noticed the bug on January 10 2023 at around 5:30pm Pacific.

**Comment by PymZoR** [comment]
Same here !

**Comment by kieferro** [comment]
Thanks for reporting this bug. This is a bug that was added by version `3.7.0`. We will release a patch as soon as possible. But if you are able to downgrade to `3.6.1` (probably rather difficult for Chrome, but definitely possible in the store for Firefox), that should solve the problem until the patch is released. Sorry for the inconvenience.

**Comment by kieferro** [comment]
The patch (3.7.1) is now published to both the chrome and the firefox extension store. Just check for updates and the problem should be fixed.
