### ISSUE TITLE
Black squares missing

### ISSUE THREAD

**Issue by j-rieck** [prettierlichess/prettierlichess#133]
OS: Mac OS 13.1
Browser: Firefox 108.0.2 (64-bit)
Add-in version: 3.7.0

The black squares dissapeared. This change happened today, as they were working fine yesterday. The squares are not highlighted when a piece is held over them either. See screenshot.

![Screenshot 2023-01-11 at 16 04 29](https://user-images.githubusercontent.com/92220/211841106-d1bf57f3-5151-4f32-9136-70f5b60fdd50.png)

This output is from the console:

```
    Scheme set
    primaryColor : undefined
    secondaryColor : undefined
    tertiaryColor : undefined
    backgroundColor : #242627 
    surfaceColor : #28292B8F
    surfaceColorHover : undefined
    defaultWhite : undefined
    textColor : undefined
    arrowPrimary : undefined
    arrowSecondary : undefined
    arrowTertiary : undefined
    arrowAlternate : undefined
    lastMove : undefined
    preMove : undefined
    moveIndicator : FFFFFF00
    boardDark : FFFFFF00
    boardLight : undefined

**Comment by kieferro** [comment]
Thank you for reporting this bug. We changed the way the board is displayed with the last update. I will look into it.
As long as the problem is not solved yet, you can simply use the last version before the change (3.6.1): [Direct link to 3.6.1](https://addons.mozilla.org/firefox/downloads/file/4039583/prettier_lichess-3.6.1.xpi)

**Comment by kieferro** [comment]
I reverted the change which most probably caused this problem. We will roll out a patch soon. This problem should only affect version 3.7.0 and 3.7.1. If you still have this bug with a higher or lower version, please reopen.
