### ISSUE TITLE
Light square bug

### ISSUE THREAD

**Issue by TheHypnotist333** [prettierlichess/prettierlichess#134]
Adjusting the light squares changes both light and dark squares. Because of this all my themes appear different than before.

**Comment by kieferro** [comment]
Which browser are you using?

**Comment by TheHypnotist333** [comment]
Chrome

**Comment by TheHypnotist333** [comment]
It is the same thing in Kiwi

**Comment by kieferro** [comment]
Ah, I assume you chose a (partially) transparent color for the Dark Square Color. That would at least explain this problem.

**Comment by TheHypnotist333** [comment]
Yes, I'm using partial transparency on the squares in my themes

**Comment by kieferro** [comment]
Closing this, as I reverted the change which caused this problem (17c2219e5d8c4e6987edf89a6399663dde6eeefe). When I re-implement the fix for Kiwi, I will make sure that this problem does not exist.
