### ISSUE TITLE
Standard Colors make the Website unreadable

### ISSUE THREAD

**Issue by Sakhr1917** [prettierlichess/prettierlichess#14]
Hello Friends!

With default Settings the Addon does not make lichess very pretty and even after playing around with the colors for a while, the text is no readable. Ist this a Bug with my firefox 86.0.1 (64-Bit) browser?

Greetings
<img width="1242" alt="Bildschirmfoto 2021-03-30 um 15 17 25" src="https://user-images.githubusercontent.com/81630492/112994946-0a950a80-916b-11eb-8e56-55b3fcd93002.png">

**Comment by noahsemus** [comment]
Hey there! The default theme of the extension is made to work with the dark background on lichess. Simply change it to that and the text should then become legible.
