### ISSUE TITLE
Opening explorer tabs crammed and overlap with settings button

### ISSUE THREAD

**Issue by younishd** [prettierlichess/prettierlichess#141]
In the opening explorer of the analysis board the 3 tabs (masters/lichess/player database) are awkwardly crammed and overlap with the settings button (gear icon).

![image](https://user-images.githubusercontent.com/994290/221284073-1e4f3fd2-0ddb-4098-909f-38b9b58fbe18.png)

Version 3.7.2
Chrome 110.0.5481.30 (Linux)

**Comment by kieferro** [comment]
I will see what I can do about this. The problem comes mainly from the fact that the evaluation bar is so much wider and therefore lacks space. I will try to find a good solution for this.
