### ISSUE TITLE
use the standard layout with the vertical layout

### ISSUE THREAD

**Issue by SergioGlorias** [prettierlichess/prettierlichess#144]
whenever I activate the vertical layout (which the names of the players are at the bottom and top of the board instead of the side)

the extension puts the rest of the site as lichess layout
even though the extension says it's in the default layout
causing having to switch the layout to default to vertical

but every now and then the extension goes back to lichess layout
having to keep switching to lichess and back to default
and that sometimes gets annoying having to be alert all the time to get what I want
![imagem](https://user-images.githubusercontent.com/9739913/226184355-54d232b0-50cf-4362-b362-17e7936dfcb8.png)

**Comment by SergioGlorias** [comment]
I'm using firefox I just saw that it's outdated buying what's in the release versions here on github

**Comment by kieferro** [comment]
I have created a fix which solves the problem when I test it locally. If you still have problems with this behavior please reopen.
