### ISSUE TITLE
in Crazyhouse analysis piece drawer doesn't slide with other elements

### ISSUE THREAD

**Issue by fipachu** [prettierlichess/prettierlichess#146]
![image](https://user-images.githubusercontent.com/80906036/226490105-70e2aea6-a550-4341-8baf-d36fe7f9b589.png)
![image](https://user-images.githubusercontent.com/80906036/226490123-35c2cb29-88b0-402c-8a26-6ce60c8bb6e0.png)

**Comment by kieferro** [comment]
Thanks for reporting this problem. I fixed it.
