### ISSUE TITLE
What is tertiary colour?

### ISSUE THREAD

**Issue by Swapneel415** [prettierlichess/prettierlichess#147]
Can anyone tell me what this database means by 'tertiary color'? 
(Question)

**Comment by kieferro** [comment]
The tertiary color is a color you can set which used at different places. For example for indicating a rating decline or a number of losses. You can look at [this](https://lichess.org/@/DrNykterstein) profile where the rating change over the last 12 games in ultrabullet, blitz and chess960 is negative. It is for example also used for indicating a deactivated [analysis board](https://lichess.org/analysis).

Does that answer your question?

**Comment by kieferro** [comment]
Closing this for now. If you still have a question please reopen
