### ISSUE TITLE
Feature Request: add a 'box' to highlight time.

### ISSUE THREAD

**Issue by Swapneel415** [prettierlichess/prettierlichess#148]
Why not add a box around the time to enhance it? Like this screenshot - https://prnt.sc/mlcub7AWYqzu and the side to move would have his box highlighted. as in the screenshot where both sides have boxes.

**Comment by claudiorrrr** [comment]
I would like to +1 the need of having a better clock on lichess (better contrast on the timing?). If we can do this with the extension it would be awesome.
