### ISSUE TITLE
Feature Request: Add a contributing guide

### ISSUE THREAD

**Issue by i-am-zach** [prettierlichess/prettierlichess#15]

**Comment by TheTrio** [comment]
Would also help if it was mentioned what linter and formatter the project uses for its css. Would help make contributions consistent with the project's style.

**Comment by Durush** [comment]
honestly we don't use any linting or formatting scheme for this project. For now the scope of this project seems small enough that missing these haven't been an issue. 

Similarly we haven't really seen any issues with the contributions from other users in terms of code standards or formatting. There are some pretty significant gaps in what you can do from a js side while creating chrome extensions. The code quality has naturally dropped as a result of these limitations. 

I'll backlog this for now, if it ever feels needed to tie down a stricter contributing process I will revisit this.

As always thanks so much for the interest in this project! We cannot believe the amount of users who are willing to contribute to this project and help us with all the bug fixes. We're super appreciative of any offered contributions!
