### ISSUE TITLE
1440p support?

### ISSUE THREAD

**Issue by kylovic** [prettierlichess/prettierlichess#150]
Currently, my prettier lichess looks like this:

![image](https://user-images.githubusercontent.com/131648842/233924097-dfedf7cc-e0f1-4c81-9132-92121e547956.png)

Is there any way to fill the screen for 1440p monitors? I'd love to have larger sidebars, especially the move list is way too small imo. Also all the space on the sides could be filled instead of being empty. Am I missing something or is this not supported yet?

**Comment by kieferro** [comment]
Thank you so much for opening an Issue. No, this is not supported yet. I will have a look at it and see how it would be possible to support that as well.
Just out of interest: The native Lichess site doesn't support this either from what I've seen, does it? If not, maybe you can open an issue in the lichess repo, if there is none on this topic yet.

**Comment by kylovic** [comment]
Well, this is what my lichess looks like when I disable prettier lichess in the Opera addons:

![image](https://user-images.githubusercontent.com/131648842/234048515-2bbb9f5f-3e97-4a76-b27f-8b809819fc53.png)

I'm not sure if lichess has any scaling/1440p support, but the board and sidebard to seem to fill the screen without the need for me to resize anything on my end, so I'd guess that lichess supports it natively?

**Comment by kieferro** [comment]
Okay, yes that seems like it is natively supported. That probably makes it easier for the plugin to do that as well. I will look into it.
