### ISSUE TITLE
Game UI bugged

### ISSUE THREAD

**Issue by janneslessmann** [prettierlichess/prettierlichess#154]
I think there was no major update as I see, but it looks like this since today and I don't know why (right side is completely bugged):  

![image](https://github.com/prettierlichess/prettierlichess/assets/125650691/b783465d-7d6b-454b-8729-fead112d519c)

Browser: Brave (latest)
Operating system: Windows 10
No other extensions installed

**Comment by kieferro** [comment]
Thank you for reporting. I will take care of it

**Comment by janneslessmann** [comment]
Thank you for dealing with it so fast c:

**Comment by kieferro** [comment]
> Thank you for dealing with it so fast c:

No problem 😃. It will still take some time until the update is rolled out though.

**Comment by kieferro** [comment]
The patch has been released and is available since yesterday for Firefox and Chrome under version 3.8.2. Please update the extension if this has not already happened automatically.
