### ISSUE TITLE
Bug: rematch, new opponent, analysis buttons broken

### ISSUE THREAD

**Issue by akilou** [prettierlichess/prettierlichess#156]
I don't know how to file an official bug report, but I can explain in words and screenshots. Everything was fine until just this morning when, after finishing a game, I can no longer click on the rematch, new opponent, or analysis buttons.

Here's a screenshot with [Prettier Lichess turned on](https://drive.proton.me/urls/XQT9WX0VHC#kgC5BTKB3LHt)

And here's the exact same page, [just with the extension turned off](https://drive.proton.me/urls/NCQA8KZ57G#C5vCfimRPbjc).

(i'd attach the images directly, but it doesn't look like I can do that)

**Comment by kieferro** [comment]
Thank you for reporting this problem. You did everything right, this is the official place to report bugs, so if you have any problems in the future, please continue to use the issue feature.

This was already reported in #154 and fixed in 000f6a58f370ece5d6e87381205f6ba10f5bf5ee. It will still take some time until the update is rolled out for the stores.



> (i'd attach the images directly, but it doesn't look like I can do that)

You should be able to drag and drop files and images into the input field for the issue text.

**Comment by akilou** [comment]
wow, what a quick response!
Thank you.

So how do I get it to work again? Can I force the extension to update or something?

--
- Drew

------- Original Message -------

**Comment by kieferro** [comment]
No problem.


> So how do I get it to work again? Can I force the extension to update or something?

Unfortunately, we have to publish the updates in the store first. Then your extension should update itself automatically. But it takes a little while until the extension is unlocked by the store.

If it is very important to you, you can also build the new version yourself and load it manually. But you need some experience with Node.js, Git and command line. [Here](https://github.com/prettierlichess/prettierlichess/blob/master/.github/CONTRIBUTING.md#build) are the basic instructions, if you need help, just ask me.

**Comment by kieferro** [comment]
The patch has been released and is available since yesterday for Firefox and Chrome under version 3.8.2. Please update the extension if this has not already happened automatically.

**Comment by akilou** [comment]
You're awesome. Thanks for caring so much about your work.

--
- Drew

-------- Original Message --------
