### ISSUE TITLE
Weird time panel

### ISSUE THREAD

**Issue by naturallyfroggy** [prettierlichess/prettierlichess#157]
![Screenshot (5)](https://github.com/prettierlichess/prettierlichess/assets/133459351/a7993c03-9389-48d9-99fa-b20622d7e0af)

**Comment by Pawnstreetblues** [comment]
it started immediately after lichess refreshed last night

**Comment by Sires0** [comment]
Also getting this

**Comment by kieferro** [comment]
Duplicate of #154

The patch has been released and is available since yesterday for Firefox and Chrome under version 3.8.2. Please update the extension if this has not already happened automatically.
