### ISSUE TITLE
Board is oversized

### ISSUE THREAD

**Issue by Pawnstreetblues** [prettierlichess/prettierlichess#160]
![Screenshot 2023-05-14 131729](https://github.com/prettierlichess/prettierlichess/assets/106215734/290edc63-2c6a-49de-b3e2-b807e6c2d549)

I downloaded the latest ver of the extension, it fixed the player window discrepancy but now the board is oversized.  If you can fix this would be appreciated, thanks in advance!

**Comment by kieferro** [comment]
Thank you for reporting this. Did this problem only occur after the update and is this only about the board on the home screen or also about the analysis board?

**Comment by Pawnstreetblues** [comment]
Hello, it occurred after the update.  It's about both the home screen and analysis.

**Comment by kieferro** [comment]
Okay, I'll look into it

**Comment by LofhJann** [comment]
Culprit seems to be commit ff89771, forcing main-max-width back to 1500px changes scaling back to original.

I suspect these changes were incorporated to resolve issue #150 but as side effect seems that 1080p scaling broke

**Comment by crafty35a** [comment]
> I suspect these changes were incorporated to resolve issue #150 but as side effect seems that 1080p scaling broke

I am experiencing this issue at 1440p, so it's not just 1080p that is broken.

**Comment by kieferro** [comment]
Thank you @crafty35a, that information is helpful. This is another argument for the solution by @LofhJann where you can adjust it yourself. I had also thought about a dynamic adjustment depending on the screen size, but that doesn't seem to make sense in this case.
