### ISSUE TITLE
 general graphics

### ISSUE THREAD

**Issue by steve01101** [prettierlichess/prettierlichess#162]
I haven't encountered any problems, but I would like to try to modify the general graphics, but I can't find the dedicated code. So, text size, square alignment, structure.

**Comment by kieferro** [comment]
The actual source code for the extension is located in the [`/src`](https://github.com/prettierlichess/prettierlichess/tree/master/src) folder. It includes the popup code as well as the CSS style sheet that gets injected by the `content.js` file. Almost all of the style changes are implemented in the [`/src/styles.css`](https://github.com/prettierlichess/prettierlichess/blob/master/src/styles.css) file, so you might simply want to change some of the rules if you only want to modify the style changes and not the behavior of the extension.
If you need more help just ask and you can also take a look [here](https://github.com/prettierlichess/prettierlichess/blob/master/.github/CONTRIBUTING.md#structure-of-the-extension) for some more explanations of the structure of the extension.
