### ISSUE TITLE
In analysis mode, the width of the opening explorer is insufficient

### ISSUE THREAD

**Issue by Siderite** [prettierlichess/prettierlichess#164]
Try selecting a user that has a long name, also go on to select multiple users and the format of the user list is quite ugly.

Second, LiChess Tools adds an extra "Me" button to Opening Explorer which is completely hidden.

**Comment by Siderite** [comment]
Somehow the size of the explorer is now OK is I resize the board. Maybe I missed it the first time. However, the names of the players that you can choose in the Opening Explorer settings are truncated no matter the resizing.

**Comment by kieferro** [comment]
> However, the names of the players that you can choose in the Opening Explorer settings are truncated no matter the resizing.

Thanks for reporting, could you maybe share a screenshot? I'm not quite sure which usecase you're talking about.

> Second, LiChess Tools adds an extra "Me" button to Opening Explorer which is completely hidden.

I'll look into that.

**Comment by Siderite** [comment]
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/d410ab07-2eac-4b83-9466-022ae9410700)

**Comment by kieferro** [comment]
Ah okay, thanks for the screenshot, I wasn't aware of that dialog box. I will take care of it.
