### ISSUE TITLE
Pretty nasty bug with embedded games in LiChess pages

### ISSUE THREAD

**Issue by Siderite** [prettierlichess/prettierlichess#165]
People often embed their games or studies into forum or blog posts on Lichess. Prettier Lichess makes them unusable:
Original view:
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/e6cb689b-e1e1-4d54-9bb7-5475cd52fdcc)
View with Prettier enabled:
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/659654a2-90c9-436e-9df4-643002725b94)
Url for this: https://lichess.org/forum/general-chess-discussion/is-this-a-good-enough-study-for-the-grunfeld

**Comment by kieferro** [comment]
Thanks for reporting!
