### ISSUE TITLE
Lichess layout change

### ISSUE THREAD

**Issue by Siderite** [prettierlichess/prettierlichess#167]
Lichess changed the design a bit. Now the options for the current game are not accessible with Prettier:
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/96caa56a-88aa-4dbd-8309-edbc93e3cef4)
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/ffa58028-6e3d-4571-a5f1-1d88901497ea)
Without:
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/6a47b09d-2567-4124-a10e-9e9bba952480)
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/74fffe59-6186-46c4-99c6-917425a4c8da)

**Comment by kieferro** [comment]
Thanks for reporting
