### ISSUE TITLE
Piece drifts to the left on clicking.

### ISSUE THREAD

**Issue by BaidDSB** [prettierlichess/prettierlichess#17]
[The issue](https://postimg.cc/xkVyq87x)

it just ruins the aesthetics a bit but more importantly leads me to pick the wrong piece if im not paying attention.

**Comment by noahsemus** [comment]
Is the shifted piece still being clicked on? How and when exactly does it shift?

**Comment by K-Sabatier** [comment]
I had this happen to me twice in the past few weeks.. It seems to happen randomly but then fixes itself after awhile, possibly after refreshing the page. When it happens, the piece I pick up hovers to the left of my cursor rather than being directly in the middle of my cursor.

**Comment by noahsemus** [comment]
I can't seem to recreate on my end. In this case I think it might be on Lichess' end as we don't mess with any of the styling on the pieces.

**Comment by BaidDSB** [comment]
I think it's working fine from this morning

**Comment by noahsemus** [comment]
Closing, feel free to reopen if you can consistently reproduce the error.
