### ISSUE TITLE
Width issues on mobile

### ISSUE THREAD

**Issue by Siderite** [prettierlichess/prettierlichess#174]
I've just recently found out that there are Chromium based mobile browsers that accept extensions, like Kiwi. Testing it I founds some issues with Prettier, too. The most annoying is the study Interactive Lesson preview mode when the width goes under 800px:
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/3f2a47cf-2382-482e-be7f-f1ffbadbb3f4)
and 400px (my own mobile):
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/8708cd5a-5ef3-4e12-8b0b-2ad9463f6796)

I think a solution for this is to just remove the octopus at under 800px.

**Comment by kieferro** [comment]
Thanks for reporting.

> I think a solution for this is to just remove the octopus at under 800px.

Yes, that seems to make sense to me as well. I'll look into it.




> Testing it I founds some issues with Prettier, too.

I don't use lichess often on my phone and therefore I don't catch all the problems there. So if you have found other problems, feel free to report them. It helps me too.

**Comment by Siderite** [comment]
Also in Analysis, for width<800px:
![image](https://github.com/prettierlichess/prettierlichess/assets/260529/e92f3df9-c7c2-4c0e-abc0-60ea80d1316d)

**Comment by Siderite** [comment]
Is there a release up coming? Because the last issue is still there on Kiwi browser (mobile). The Explorer is out of screen on the left side and only gets in the correct place when the computer analysis is on.

**Comment by kieferro** [comment]
Sorry for the delay, I have published a release here on Github and hopefully it will also be available in the stores soon.
