### ISSUE TITLE
Blue and Yellow arrow colors are reversed

### ISSUE THREAD

**Issue by Siderite** [prettierlichess/prettierlichess#177]
At first I just thought it was a design choice, but then I realized that it's probably a slip-up: When you draw arrows or circles on the screen, the style for blue shapes shows yellow arrows and circles and viceversa.

**Comment by kieferro** [comment]
Although I'm not the one who decided or implemented this, I'm not entirely sure that it's a slip-up. With the default settings, the playing field is white and blue, which causes yellow arrows/circles to have much more contrast. So I think it makes sense to swap blue and yellow (although you can always change this in the settings).

I'm always happy to implement change requests, but what would be the advantage of having it the other way around by default than it currently is?

**Comment by Siderite** [comment]
It's just weird that the brush named "blue" renders yellow and the one called "yellow" renders blue. If the arrows have a meaning, then enabling/disabling Prettier Lichess swaps that meaning. Anyway, if it was intended, I don't see a big problem with this.
