### ISSUE TITLE
Unstyled sections of Interactive Lessons

### ISSUE THREAD

**Issue by Siderite** [prettierlichess/prettierlichess#181]
If the Lichess background is set to Light , then Prettier Lichess changes everything to a darker shade, except some things like labels in the Interactive Lesson UI for authors

![image](https://github.com/prettierlichess/prettierlichess/assets/260529/5e03fdeb-86f8-4c10-b6cc-490d64b1493b)

**Comment by kieferro** [comment]
Thanks, I hadn't considered the interactive lesson for authors before when styling. I will definitely change that later. If you have any other places that look weird in light mode, always feel free to report them. Dark mode is recommended, but ideally all elements should be styled actively.

**Comment by Siderite** [comment]
Of course. I am sure you would do the same if you found any issues with my Lichess extension :D
