### ISSUE TITLE
UI problem when using voice recognition

### ISSUE THREAD

**Issue by fishcomefromthemilk** [prettierlichess/prettierlichess#183]
I am disabled so I use voice commands. When I speak, the previewed text temporarily makes the board size smaller and it's distracting.

[clip](https://youtu.be/d_NRk-jICMo)

**Comment by kieferro** [comment]
Thanks for reporting. I've fixed it and we'll publish the update soon

**Comment by fishcomefromthemilk** [comment]
Awesome! Thanks for supporting disabled people and stuff, or something like
that. I appreciate it!
