### ISSUE TITLE
Adding Prettier Lichess to Lichess

### ISSUE THREAD

**Issue by shermansiu** [prettierlichess/prettierlichess#184]
@kieferro, How do you feel about making Prettier Lichess (or at least something similar) the default style for Lichess? Did the lead devs decline a previous request to update Lichess' style? If not, would this something you'd seriously consider?

Obviously, there would be some minor changes, such as the addition of a main _light_ theme to go with the dark and possibly making the style more consistent with Veloce's new mobile app. But I think that an aesthetic overhaul is long overdue and welcome.

**Comment by shermansiu** [comment]
Moreover, perhaps the colours could be chosen so that they are more similar to Lichess' OG colours (yes, I'm aware of the OG Lichess theme here).

**Comment by kieferro** [comment]
I don't know if it would be quite as easy as you imagine. Lichess does not use vanilla CSS, but [Sass](https://sass-lang.com/documentation/). This means that a PR that changes the entire styling couldn't just add the prettierlichess styling files but would need to work all the new styles into the already existing styling structure of lichess.
Of course, that would still be possible and I'm happy to help if that is desired. But I'm not sure that a fundamental style change is the highest priority for the Lichess dev team right now. That would be a very big change that would require a corresponding amount of work and review. There are already some open [issues about a style change](https://github.com/lichess-org/lila/issues/12829) without any answers.

> Did the lead devs decline a previous request to update Lichess' style?

No, but they are definitely [aware that the extension exists](https://github.com/lichess-org/lila/issues/11224). It is also linked on lichess itself: https://lichess.org/page/extend
In general, lichess has a relatively large ecosystem of extensions that offer a good opportunity to add an optional feature that should not become part of the official site.


As much as I'm glad that you like the style of the extension so much that you'd like to see it built into lichess, I think it would make more sense if you first start the discussion about a potential layout and style change in the [official lichess repo](https://github.com/lichess-org/lila) and see if there is the interest and resources for it. If that's the case, feel free to cite prettierlichess and mention me.
But as long as there is no explicit wish from the dev team for a style change, my own ambitions to incorporate the style of the extension into Lichess are relatively small.

**Comment by shermansiu** [comment]
On the Discord, it was confirmed that they don't have a triaged roadmap of features to add, but some members of the dev team are working on adding better bots and ornicar is working on adding internationalization and bug fixes.

However, it was confirmed that it's unlikely that even if a PR for Prettier Lichess _was_ written, that it would be merged.

![image](https://github.com/prettierlichess/prettierlichess/assets/12627125/e9ada656-6150-4da4-a4d5-6fe959f323d0)
