### ISSUE TITLE
Frontpage blog bar layout is broken

### ISSUE THREAD

**Issue by LofhJann** [prettierlichess/prettierlichess#185]
![image](https://github.com/prettierlichess/prettierlichess/assets/22809779/2c62e9b7-25f2-4c03-a4d6-57e735d678ee)

Layout for blog posts shown on frontpage has been changed on official layout and changes have caused display issues in PrettierLichess. If author name is set, photo and author name are displayed wrong. Element inspector shows that layouts for "authorless" and "authored" blog post-cards seem to also be quite different

New official layout 
![image](https://github.com/prettierlichess/prettierlichess/assets/22809779/b1db5409-2c72-45aa-bf2e-ccce5437d305)

**Comment by kieferro** [comment]
Thanks for reporting and sorry for the delay. I will upload the new version tomorrow
