### ISSUE TITLE
Embedded Games in forum not showing

### ISSUE THREAD

**Issue by orc4n** [prettierlichess/prettierlichess#19]
Title says it all, here's a quick example:
https://lichess.org/forum/general-chess-discussion/i-am-tired-of-losing-games-due-to-blindly-hanging-pieces-and-getting-mated-in-a-silly-way?page=1

Colour-Profile in case it has something to do with it:
{
  "primaryColor": "#82D797DB",
  "secondaryColor": "#E8A43E",
  "tertiaryColor": "#B84C4C",
  "backgroundColor": "#182937",
  "surfaceColor": "#233644",
  "surfaceColorHover": "#345269",
  "defaultWhite": "#CECEF5"
}

Appreciate your work :)

**Comment by noahsemus** [comment]
Thanks for the report. Just took a look and implemented a fix. Should be fixed in the next update!
