### ISSUE TITLE
Lichess TV menu is off center

### ISSUE THREAD

**Issue by TheHypnotist333** [prettierlichess/prettierlichess#193]
On the left side where you select what to watch.
![hdgf](https://github.com/prettierlichess/prettierlichess/assets/104811236/49ef02ca-0845-4afc-bf89-484684f60fb0)

**Comment by nloding** [comment]
Hi there! Thanks for reporting the issue and for using Prettier Lichess. Apologies that it's taken so long to address it. Sometimes life can get in the way of open source maintenance, but we're back and have fixed the major issues in the new release! This fix should be included, but please us know if you still have issues. It's already available for Firefox, and will be available once the Chrome store approves it, which can sometimes take a day or two.
