### ISSUE TITLE
Home destroyed designe

### ISSUE THREAD

**Issue by Conimbad** [prettierlichess/prettierlichess#195]
Hello there, I just report the lichess home page issuese.
Is nothing in its place.
![Screenshot 2023-12-30 at 19-10-00 The best free adless Chess server](https://github.com/prettierlichess/prettierlichess/assets/7676442/c0b3036d-2df9-43ef-91f1-67b1afb2d749)

**Comment by Ridhubharan** [comment]
Quick fix: Click on the prettier lichess extension, change the layout to  "Lichess layout".  DON'T CLOSE THIS ISSUE AS IT IS JUST A WORK AROUND AND IT NEEDS TO BE SOLVED.

**Comment by LofhJann** [comment]
Can confirm. Duplicate issue with #198.

I don't have windows device handy right now to test but this could be scaling related issue.

M1 Macbook pro here as in linked issue.

**Comment by LofhJann** [comment]
After further investigation I've found culprit.

Home page has been updated with new element  'lobby__feed' which isn't accounted in grid and that's why it no longer fits.

**Comment by Aparikk** [comment]
Same here :>

**Comment by nloding** [comment]
Hi there! Thanks for reporting the issue and for using Prettier Lichess. Sometimes life can get in the way of open source maintenance, but we're back and have fixed the major issues in the new release! This fix should be included, but please us know if you still have issues. It's already available for Firefox, and will be available once the Chrome store approves it, which can sometimes take a day or two.
