### ISSUE TITLE
Improper layout

### ISSUE THREAD

**Issue by Golden00755** [prettierlichess/prettierlichess#198]
<img width="1420" alt="2024-01-08_10-51-16" src="https://github.com/prettierlichess/prettierlichess/assets/155961873/64b62a14-646d-4c19-a32e-9a6c36ece5e1">
<img width="1202" alt="2024-01-08_10-51-22" src="https://github.com/prettierlichess/prettierlichess/assets/155961873/06ce0409-40ea-4763-84a2-3e105c8d64e9">

MacBook Air M1, Arc browser

**Comment by nloding** [comment]
Hi there! Thanks for reporting the issue and for using Prettier Lichess. Sometimes life can get in the way of open source maintenance, but we're back and have fixed the major issues in the new release! This fix should be included, but please us know if you still have issues. It's already available for Firefox, and will be available once the Chrome store approves it, which can sometimes take a day or two.
