### ISSUE TITLE
Visual bugs on premoves and move indicators

### ISSUE THREAD

**Issue by instructionmanual** [prettierlichess/prettierlichess#20]
I've noticed that PL doesn't show the premove indicator over the last-move indicator.  The first two images below show this.

First image is default lichess, which shows a darker square on the square you are intending to premove to.  However, on PL, if you premove to a square that a piece has just moved to, the lighter "last-move" square color is shown instead of the premove color.  This isn't a huge issue, but it is easier to confirm a premove if the intended square shows the premove color instead of the last-move color.  

![Lichess Default Premove](https://user-images.githubusercontent.com/81769016/113327192-a435f680-92e8-11eb-80b8-399341d0b5de.png)

In this image, I have just moved the bishop and I am premoving the queen to recapture if the bishop is captured.  The queen's premove is shown over the last move indicator.

![Prettier Lichess premove](https://user-images.githubusercontent.com/81769016/113327194-a4ce8d00-92e8-11eb-8991-6f28341aeda8.png)

In this image, I am premoving the h pawn to capture if the g pawn is captured.  The pre-move color does not show over the last-move color.

---

The second visual bug I noticed is this one, where one of the possible move dots is dimmer than the rest.  Image below:

![prettier lichess dimmer square](https://user-images.githubusercontent.com/81769016/113327193-a4ce8d00-92e8-11eb-9e4a-df97aacc6c4d.png)

I am running 87.0 (64-bit) Firefox.

**Comment by noahsemus** [comment]
Thanks for the report, will look into this now.

**Comment by yoder449** [comment]
This might be a Lichess issue, but I've noticed that the highlights are sometimes off by 1 pixel as shown below. 

I cannot replicate or discern a pattern, but sometimes it seems more pronounced than others. Ive attached a pic below to show it at it's worst condition.

![image](https://user-images.githubusercontent.com/50274042/113792228-67686600-9713-11eb-913f-19d82a00dcae.png)

This is directly related to this issue's title, so I thought adding this here would be appropriate. Thank you for your work on this extension!

**Comment by noahsemus** [comment]
Having looked into this before, it seems to be a Lichess issue with how they size the board. We can't really mess with this too much as they have their JS for resizing the board utilizing a few different variables in the CSS as well.

**Comment by noahsemus** [comment]
Closing this for now, as it doesn't seem to be the extension's issue.
