### ISSUE TITLE
Mainpage middle box/area not showing

### ISSUE THREAD

**Issue by vicsnorr** [prettierlichess/prettierlichess#200]
Hi!

I have an issue with the prettier Lichess extension using Firefox. On the mainpage of lichess, the middle box/area is tiny not allowing me to select a new random game for example.
I have added a screenshot with the mainpage.
I'm running the latest version of Firefox and prettierlichess.

Thank you!
Victor
<img width="1540" alt="Screenshot 2024-03-05 at 15 53 17" src="https://github.com/prettierlichess/prettierlichess/assets/81190769/ba27c3f8-4b18-40c5-a93a-72f4547fa9e5">

**Comment by LofhJann** [comment]
It's known issue I and few others have reported in issues #195, #192 and #200. 

Temporary workaround has been suggested by user wongdq in comment https://github.com/prettierlichess/prettierlichess/issues/192#issuecomment-1870050176

**Comment by nloding** [comment]
Hi there! Thanks for reporting the issue and for using Prettier Lichess. Sometimes life can get in the way of open source maintenance, but we're back and have fixed the major issues in the new release! This fix should be included, but please us know if you still have issues. It's already available for Firefox, and will be available once the Chrome store approves it, which can sometimes take a day or two.
