### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by LofhJann** [prettierlichess/prettierlichess#201]
It's been 5 months since last changes to codebase and 3 months since issue #195 that breaks functionality completely. 

Chrome extension currently has over 8000 users (as per Chrome Web Store) with Firefox sitting near 1000 as well, so it's quite extensively in use (or was before it broke). As per open source projects usual, the support isn't guaranteed and projects die since there's no obligation to keep up the support, and if we're at the end of the line I'm extremely grateful that prettierlichess had the life as long it had.

As a contributor for prettierlichess I'm respectfully asking whether the codebase is completely abandoned by owner? In that case marking it as archived might be worth it, to signal possible contributors not to waste their time on it. Removing extension from Chrome and Firefox stores might be another good step to take if no updates are ever planned again, since as stated above in current form the extension is not functional and shouldn't be offered for end users.

**Comment by nloding** [comment]
Hi @LofhJann - thanks for the previous contributions! And thanks for the patience. Life gets in the way of side projects some times. We are working on a new release - I don't have an ETA for the release yet, but it's coming with all the necessary fixes!

**Comment by nloding** [comment]
And the release is out! It's already available for Firefox, and will be available once the Chrome store approves it, which can sometimes take a day or two.
