### ISSUE TITLE
Top bar layout misplaced

### ISSUE THREAD

**Issue by Gundarl** [prettierlichess/prettierlichess#202]
The top bar layout was fine until yesterday but is misplaced.

Windows 10, Chrome, Reinstalled extension but same.
Anyone else having the same issue?

![lichess](https://github.com/prettierlichess/prettierlichess/assets/160199815/afc2ad82-949c-408d-a9f3-0cccba144e23)
![image](https://github.com/prettierlichess/prettierlichess/assets/160199815/93e7d0ec-8c94-4334-a533-c0aa93a38c29)

**Comment by adrien-lsh** [comment]
The navbar seems to be glitched yeah...
Using firefox.

![image](https://github.com/prettierlichess/prettierlichess/assets/50402620/e7cdd71f-3211-48ca-a7b0-a211f344d180)

**Comment by nloding** [comment]
Hi there! Thanks for reporting the issue and for using Prettier Lichess. Sometimes life can get in the way of open source maintenance, but we're back and have fixed the major issues in the new release! This fix should be included, but please us know if you still have issues. It's already available for Firefox, and will be available once the Chrome store approves it, which can sometimes take a day or two.
