### ISSUE TITLE
Top navigation bar still needs a fix.

### ISSUE THREAD

**Issue by Gundarl** [prettierlichess/prettierlichess#205]
Thanks to all the devs for updating this great extension.

However, the top navigation bar still needs a fix. 
If I remember correctly, the buttons on top were centered and transparent.

Extension version: 3.12.0
Browser: Chrome
![image](https://github.com/prettierlichess/prettierlichess/assets/160199815/39c65170-0ca5-467f-b5a1-8f71603f1712)
![image](https://github.com/prettierlichess/prettierlichess/assets/160199815/d4dcc4c7-8c4d-4fd9-b911-561cd2385ed3)
![image](https://github.com/prettierlichess/prettierlichess/assets/160199815/7b556a57-f276-4f54-a7de-737c627da245)

**Comment by nloding** [comment]
Hi @Gundarl - I can't reproduce this with Chrome. Do you have any other extensions applying custom styles or scripts? Based on your screenshots, it looks like you may have something else in addition to Prettier Lichess.

**Comment by Gundarl** [comment]
Hi @nloding ! 

That's strange. I removed all extensions on Chrome and reinstalled prettier lichess, but still facing the same issue.
I even installed Firefox browser for the first time and installed the extension but it looks the same as on Chrome. 
I'm not sure if it's just a weird bug on my end. I'll try again on my other PC.

**Comment by kieferro** [comment]
Are you by any chance using a screen with a high resolution? It may also have something to do with that.
