### ISSUE TITLE
Missing timeline indicator in arena

### ISSUE THREAD

**Issue by alain-picard** [prettierlichess/prettierlichess#21]
When using prettier lichess, the red line indicating the current time in the area tournaments page 
disappears (or is invisible).

This is the CSS selector which needs to have a border-left colored property of some sort.

#main-wrap > main > section > div.tour-chart > div > div.timeline > div.timeheader.now

Thanks for prettier lichess!  It really is prettier! ;-)

**Comment by noahsemus** [comment]
Thanks for the report. Should be fixed in the next update (also this page will be styled in a future future update 👍 )
