### ISSUE TITLE
Analysis board is very broken

### ISSUE THREAD

**Issue by nloding** [prettierlichess/prettierlichess#214]
Not sure what Lichess changed between yesterday and today, but now the analysis board is completely broken:
<img width="1484" alt="image" src="https://github.com/prettierlichess/prettierlichess/assets/328425/1a9f6767-47a4-4f04-a570-28548c42bcd1">

**Comment by quasicredible** [comment]
![lichess broken](https://github.com/prettierlichess/prettierlichess/assets/122417379/44e2e5fe-d915-4745-b8ef-379c5169ad46)

Mine looks even worse.

**Comment by Gundarl** [comment]
Same here. Came to see if I was the only one.

**Comment by ducketyduck** [comment]
It's funny how we just got a fix for the front page being bugged and now there's already another similar issue
