### ISSUE TITLE
Bug Report - Analysis (Prettier Lichess)

### ISSUE THREAD

**Issue by ThePlayzPaidOff** [prettierlichess/prettierlichess#218]
Hello, for some reason analysis is broken for me and I am not sure why. Hopefully this is fixed soon?
https://i.imgur.com/uhldTUX.png

**Comment by kieferro** [comment]
We already released a fix for this yesterday, but the Chrome Store review is still ongoing. When the review is finished (hopefully today or tomorrow) the new version will be available immediately. The version for Firefox is already available, so if you use that, please reopen, the bug should already be fixed there.

**Comment by kieferro** [comment]
The update is now also available for Chrome. If you still have issues please reopen.

**Comment by ThePlayzPaidOff** [comment]
Just saw the update, it resolved. Thank you so much! :)
