### ISSUE TITLE
Buttons names too long in different languages.

### ISSUE THREAD

**Issue by Knayder** [prettierlichess/prettierlichess#23]
In different languages (polish in my example), buttons names are too long and are getting moved to the next line which is on top of the board.
![image](https://user-images.githubusercontent.com/19751594/113424657-cc992000-93d0-11eb-8c38-efb18326dc2b.png)
![image](https://user-images.githubusercontent.com/19751594/113424698-df135980-93d0-11eb-86d7-7740879ebe8f.png)
English: Puzzles
Polish: Zadania szachowe

**Comment by noahsemus** [comment]
Thanks for the report! Fixed in next update.

**Comment by Knayder** [comment]
![image](https://user-images.githubusercontent.com/19751594/113790464-b7f6b800-9741-11eb-9d14-435547054410.png)
It's great now. Thanks :D
