### ISSUE TITLE
Bug With Practice Sidebars

### ISSUE THREAD

**Issue by Sean-Ker** [prettierlichess/prettierlichess#24]
Thanks for the awesome extension! 

Just found a small bug in the Practice section of Liches [[Learn -> Practice](https://lichess.org/practice/rook-endgames/7th-rank-rook-pawn)]. It seems like the sidebar on the right disappears with the extension enabled. Please see the screenshots attached below. Thanks.

![image](https://user-images.githubusercontent.com/38770139/114201499-42970d00-9924-11eb-8a5a-de0372174bc0.png)
![image](https://user-images.githubusercontent.com/38770139/114201516-44f96700-9924-11eb-8fbb-f143675c143a.png)

**Comment by noahsemus** [comment]
Thanks for the report. Looking into this now.
