### ISSUE TITLE
Challenges and play against the computer options are missing

### ISSUE THREAD

**Issue by algertc** [prettierlichess/prettierlichess#26]
As far as I can tell, there is currently no way to play the computer or challenge someone with a link with the extension enabled. The option is usually on the right along with the create a game button which is removed.

**Comment by noahsemus** [comment]
These have now been moved to the bottom of the homepage ->

![image](https://user-images.githubusercontent.com/33107099/114406752-c98ef400-9b75-11eb-823a-ea71326d135c.png)
