### ISSUE TITLE
The games embedded in some blog posts are missing with the extension enabled

### ISSUE THREAD

**Issue by sebzim4500** [prettierlichess/prettierlichess#27]
See for example https://lichess.org/blog/W3WeMyQAACQAdfAL/7-piece-syzygy-tablebases-are-complete

**Comment by noahsemus** [comment]
Thanks for the report. This is fixed in the next update!

**Comment by orc4n** [comment]
This problem seems to be back. blogs as well as forums
example: https://lichess.org/forum/general-chess-discussion/stockfish-1-3

**Comment by noahsemus** [comment]
Just pushed 3.1.0 about an hour ago and it has just published to the store. This should fix this problem.

**Comment by orc4n** [comment]
Thanks for your effort, really appreciate it :)
