### ISSUE TITLE
Horrible Visual Bug

### ISSUE THREAD

**Issue by LudamStudio** [prettierlichess/prettierlichess#28]
I'm using the extension in the Vivaldi (Chromium) browser, and the letters just can't be seen. Absolutely nothing can be read.
![image](https://user-images.githubusercontent.com/71848144/114748485-9ab08380-9d17-11eb-8547-b91d939c7457.png)
![image](https://user-images.githubusercontent.com/71848144/114748528-a308be80-9d17-11eb-8e93-126012a4af79.png)

I already propose a simple solution, an **option to change the color of the letters**. So we can select which one best suits the theme, and combine colors. This is urgent.

Thank you very much for making this incredible extension

**Comment by noahsemus** [comment]
Thanks for the issue. This is due to the fact the default theme is made to use the Lichess dark background. That should set the text to the correct color. Essentially the Lichess "Background" setting will set the text color of the site.
