### ISSUE TITLE
Coordinates not showing up inside the board

### ISSUE THREAD

**Issue by jkner** [prettierlichess/prettierlichess#29]
Settings: 
![image](https://user-images.githubusercontent.com/50881273/115138098-afc73400-9fef-11eb-82b7-35ac72bb546f.png)

Still outside:
![image](https://user-images.githubusercontent.com/50881273/115138102-b786d880-9fef-11eb-8b74-c61565fc9cdb.png)

**Comment by noahsemus** [comment]
This feature is being worked on being included in the next update. Thanks for the report!

**Comment by noahsemus** [comment]
This feature is now supported
