### ISSUE TITLE
Page Numbers on Forum Pagination Not Visible

### ISSUE THREAD

**Issue by robertswa** [prettierlichess/prettierlichess#31]
The pagination numbers under the 'forum' section are the same color as the top horizontal green bar under the default color scheme. Only the 'current' page is visible by default. Other numbers are visible only on mouseover.

**Comment by noahsemus** [comment]
Hey again! Thanks for throwing this on GitHub. Looking to fix now...

**Comment by noahsemus** [comment]
This is now fixed in the next update!
