### ISSUE TITLE
custom board colors affecting coordinates on the side of the board

### ISSUE THREAD

**Issue by birdegy** [prettierlichess/prettierlichess#32]
>
![Screenshot_20210424-125835_Kiwi Browser](https://user-images.githubusercontent.com/83119485/115956538-a06b4d80-a4fd-11eb-9ef4-b6d338e5d2b1.jpg)
![Screenshot_20210424-125831_Kiwi Browser](https://user-images.githubusercontent.com/83119485/115956539-a19c7a80-a4fd-11eb-92f0-8387c2409cb4.jpg)

**Comment by noahsemus** [comment]
If you're using Lichess' default board sets or another extension's, make sure to click "Don't use custom board colors". This should reset the coordinates to Lichess' default colors.
