### ISSUE TITLE
Cursor position detection is bugged, resizing the board fixes the problem temporarily

### ISSUE THREAD

**Issue by kasi-mir33** [prettierlichess/prettierlichess#33]
I saw this issue: https://github.com/prettierlichess/prettierlichess/issues/17

and I'm experiencing a similar problem. It's always resolved when manually resizing the board (which is possible despite having the option "Show board resize handle" on NEVER) or turning off Prettier Lichess in the addons manager.

I'm using Firefox v88 but I was able to recreate the same problem with Chrome. 

Here are some screen recordings to demonstrate the issue: https://streamable.com/rtr8b1 https://streamable.com/r82zmr

**Comment by kasi-mir33** [comment]
I enabled the extension again after seeing your post on reddit from yesterday and it seems the issue is fixed now.

**Comment by noahsemus** [comment]
This should finally now be fixed in the next update!

**Comment by kasi-mir33** [comment]
> This should finally now be fixed in the next update!

Awesome, thanks! I'm curious what ended up being the cause of this bug?

**Comment by noahsemus** [comment]
It came from the evaluation bar animation for opening and closing. Initially we did it through css transforms, which isn't picked up as part of the layout, therefore creating the bug. All there was to do was change it from a transform to a margin-left and voila!
