### ISSUE TITLE
Default premove color is extremely hard to see

### ISSUE THREAD

**Issue by crafty35a** [prettierlichess/prettierlichess#35]
With the default settings, the premove color is nearly invisible (especially on dark squares, but even on light squares it is very hard to see). Here is a screenshot with b4 premoved:
![image](https://user-images.githubusercontent.com/1082003/117022284-1de54980-acc6-11eb-8b9d-67c8f797693b.png)

And here is what the same premove looks like without Prettier Lichess:
![image](https://user-images.githubusercontent.com/1082003/117022948-aa900780-acc6-11eb-8917-2d366e204e34.png)

Everything else seems to work great. Thanks for your work on this!

**Comment by noahsemus** [comment]
Darkened in the next release!
