### ISSUE TITLE
The icons and fonts changed suddenly

### ISSUE THREAD

**Issue by LudamStudio** [prettierlichess/prettierlichess#37]
The icons and fonts suddenly changed. It seems that it is an error of the extension, since Lichess by default does not have these errors. Is it only happening to me or is it a general error?
![image](https://user-images.githubusercontent.com/71848144/117856656-7e89fe80-b251-11eb-8316-ff32628a1b4d.png)
![image](https://user-images.githubusercontent.com/71848144/117856704-8ea1de00-b251-11eb-8143-9e7c57664fef.png)

**Comment by noahsemus** [comment]
This was due to an update on Lichess' end. Now fixed!
