### ISSUE TITLE
API reference is unreadable

### ISSUE THREAD

**Issue by KnightosMaster** [prettierlichess/prettierlichess#38]
Hello,

The color changes also apply to the [API documentation](https://lichess.org/api), and with my color settings it is mostly unreadable.

![image](https://user-images.githubusercontent.com/655652/117939725-a6886900-b308-11eb-9d05-e0bfe5092296.png)

Is it possible to make specific pages exempt from the styling changes? Of course disabling the extension is a possible workaround, but it'd be nice if I didn't have to do it every time.

I'm using Firefox 88 on Linux.

Thank you for your work anyhow!

**Comment by noahsemus** [comment]
Will look into possibly disabling the extension here -- otherwise will have to style to make legible.

**Comment by noahsemus** [comment]
Disabled the extension on this page! Will be out in the next update.

**Comment by TheTrio** [comment]
Was thinking about styling the API page. Is this issue still open?

**Comment by noahsemus** [comment]
Feel free to create a PR to style the page!
