### ISSUE TITLE
Homepage element sizes all shifted since most recent update

### ISSUE THREAD

**Issue by MatthewMaginniss** [prettierlichess/prettierlichess#40]
Specs:
Firefox 88.0.1 (64-bit) (Most recent version)
2560x1440 resolution
Prettier Lichess v3.0.0

My firefox and extensions updated this morning and logging into Lichess this is how the homescreen looks 
![image](https://user-images.githubusercontent.com/6898931/118499633-1fb30200-b6f5-11eb-9929-c67a07b0a922.png)
![image](https://user-images.githubusercontent.com/6898931/118499663-280b3d00-b6f5-11eb-8eb1-bd06eeef6cda.png)

I have disabled all other extensions to make sure it was not something else effecting this and it does not appear so at least. Please let me know if I can do anything to help.

Note: This does not happen on 1920x1080 monitors. Only on the 2560x1440.

**Comment by noahsemus** [comment]
Looking into this now!

**Comment by noahsemus** [comment]
Fixed in the next update! Should be rolling out in a day or two.

**Comment by MatthewMaginniss** [comment]
Awesome!

Thank you so much @noahsemus Love the extension.
