### ISSUE TITLE
Lichess streamer mode

### ISSUE THREAD

**Issue by noahsemus** [prettierlichess/prettierlichess#41]
"I would absolutely love an option to be able to display the clocks, names, and ratings of opponents at the top and bottom of the board.

As a Lichess streamer, I often envy Chess.com users who are able to cleanly display all that information together."

~ u/tylercruz

**Comment by TheTrio** [comment]
Here's what I've got right now

![final](https://user-images.githubusercontent.com/10794178/118721361-606f6000-b848-11eb-8437-a21dd888d332.png)

Some points to note

1. The coordinates should ideally be inside the board. Or the username and time on the bottom should have some extra margin/padding. 
2. Perhaps the panel on the right should not be the size of the board. Not sure.

Also, I have no idea about browser extensions, so I've just changed the css directly. I suppose there's a way to enable/disable css using the extension.

Do let me know what you think.

**Comment by noahsemus** [comment]
Hey, thanks for this! However, we already have a [branch going ](https://github.com/prettierlichess/prettierlichess/tree/streamer-mode) and it is fully styled. We're currently working on the toggle to turn streamer mode on and off. Thanks again, though!

**Comment by TheTrio** [comment]
Aah. No worries. 

Probably should've checked if there were any branches for this before starting. 

Sorry for the confusion!

**Comment by Durush** [comment]
Closing this as we've implemented a streamer mode now
