### ISSUE TITLE
Certain color issues on the board

### ISSUE THREAD

**Issue by mimecry** [prettierlichess/prettierlichess#42]
Hi, thank you for this amazing extension! I'd like to submit the following bug report:

I noticed that during an actual game (as opposed to doing analysis), there are some inconsistencies where the background of a square isn't fully highlighted.  

In the picture below, you can see the right edge of the c7/c5 squares not being filled all the way. Every square on the leftmost file of the board (a/h depending on perspective), as well as the dark colored squares on the topmost row (1/8) also exhibit these artifact to varying degrees

![image](https://user-images.githubusercontent.com/10742312/118581383-c2ce4f00-b7bb-11eb-882b-4b9f15973af3.png)

**Comment by noahsemus** [comment]
This is a bug we've seen pop up every now and then -- as far as we're aware it seems to be an issue on Lichess' end.

**Comment by Durush** [comment]
I think for now we're going to close this issue out unless we can find away to recreate this consistently. Please reopen this issue if this bug starts happening consistently or a pattern for causing it is determined.

Thanks!

**Comment by mimecry** [comment]
sorry for not doing so earlier, i forgot to check github. i'll see if i can manage to reproduce the issue 100% and let Lichess know about it

**Comment by Durush** [comment]
No worries, I was just cleaning up some of the issues that seemed they might have been inactive. If you are able to tie it back to this extension please feel free to reopen this we can try to investigate further. 

if it isn't happening without the extension over multiple board sizes (I would try to match the vanilla lichess board size to roughly what it was sizing to with our extension). Here are a few validations I would ask for:

1. does this issue occur both with or without custom board colors enabled in the popup?
2. does a quick resize of the board or refresh of the page fix this issue?
3. What is your monitor resolution/does this error persist regardless of window sizes?
