### ISSUE TITLE
No Eval Bar after Puzzle complete

### ISSUE THREAD

**Issue by luhann** [prettierlichess/prettierlichess#48]
Hi, thank you for the awesome work you guys do. I love the extension. 

I've noticed on all three browsers I've tried on (Edge, Chromium, and Firefox) after completing a puzzle and looking at the engine eval, there is no eval bar visible except for a faint line where the eval bar should be. When I turn off the extension the eval bar is present and when turned back on the eval bar no longer appears.

See example here:

![image](https://user-images.githubusercontent.com/22576145/118883125-6f0b5500-b8e4-11eb-9159-8385b69cbf84.png)

**Comment by noahsemus** [comment]
The eval bar has been temporarily removed for now from puzzles.
