### ISSUE TITLE
Different boards shifted to the left

### ISSUE THREAD

**Issue by Rishabh672003** [prettierlichess/prettierlichess#50]
Specs- Brave Version 1.24.85 Chromium: 90.0.4430.212
1080p resolution
zoom is 100%
<img width="960" alt="Image 196" src="https://user-images.githubusercontent.com/53911515/118962050-99135480-b982-11eb-86c3-faf012844f53.png">
<img width="960" alt="Image 197" src="https://user-images.githubusercontent.com/53911515/118962069-9c0e4500-b982-11eb-925d-8c73f9c26f8a.png">
<img width="960" alt="Image 198" src="https://user-images.githubusercontent.com/53911515/118962081-a0d2f900-b982-11eb-87db-bc9bd6b47fee.png">
![Image 194_LI](https://user-images.githubusercontent.com/53911515/118962085-a2042600-b982-11eb-926e-f2acf21c4a3b.jpg)
<img width="960" alt="Image 195" src="https://user-images.githubusercontent.com/53911515/118962087-a3355300-b982-11eb-84ac-c6e9a7f71f18.png">
I even also checked this on firefox(when the zoom is 110%) and edge and they also have the same problem.
also in edge the colors look weird-
![Image 193](https://user-images.githubusercontent.com/53911515/118963141-c7ddfa80-b983-11eb-9ed9-16218487d1c4.png)
hope you look into this and fix this.

**Comment by noahsemus** [comment]
Looking into the responsive sizing now. On Firefox and Chrome, these issues don't seem to come up at 100% zoom. As of now, we officially don't support Edge or Brave, so we won't be addressing bugs that come up with those browsers.

**Comment by Rishabh672003** [comment]
I checked on chrome and the problem still persists for me-
![Image 199](https://user-images.githubusercontent.com/53911515/119001892-05557e80-b9aa-11eb-80ba-0a20b8ad1385.png)

is there something wrong in my end or what?

**Comment by TheTrio** [comment]
I suppose this is similar to #43 and #51 @noahsemus? This issue seems to come up a lot lol.

**Comment by noahsemus** [comment]
It seems to be happening on the second desktop breakpoint when the height of the viewport is not super high res. Will look into a fix now.

**Comment by noahsemus** [comment]
These issues should be resolved in the next update.

**Comment by Rishabh672003** [comment]
oh ok thanks
