### ISSUE TITLE
Crooked Board

### ISSUE THREAD

**Issue by Starbugg** [prettierlichess/prettierlichess#56]
Since a couple of days the lines on the board, while playing, are not straight.
![chrome_6Gk8mQcNt3](https://user-images.githubusercontent.com/85575203/121221049-7be8ec00-c885-11eb-9593-c7cd352f420c.png) As seen in the picture the shift a pixel or two.

This happens during all variants where I play myself as well as TV, but not on the homepage. 
I use the chrome extension.

Appreciate the work.

**Comment by orc4n** [comment]
Same of firefox as well.
It seems like the alignment of the last-move box is a bit off as well.
![mismatch](https://user-images.githubusercontent.com/62054727/121867452-4407fb80-cd00-11eb-93cd-5cdb627ba39c.png)
![corners_mismatch](https://user-images.githubusercontent.com/62054727/121867481-48ccaf80-cd00-11eb-88d8-3cc8a894db94.png)

**Comment by noahsemus** [comment]
This should be fixed in the next update. This seemed to arise from how the web renders gradients -- so I added a decimal to the percentage on the repeating-conic-gradient to get a small blur that will fix it.
