### ISSUE TITLE
Counters overlap on homepage

### ISSUE THREAD

**Issue by t-stev** [prettierlichess/prettierlichess#57]
The "Player Count" and "Games in Play" counters overlap on the homepage. I fixed it by getting rid of the flex nonsense in the "lobby__counters" CSS property.

Before:
```
.lobby__counters {
    position: relative !important;
    order: 1 !important;
    display: flex !important;
    flex-direction: row !important;
    align-items: center !important;
    justify-content: center !important;
    width: 80% !important;
}
```
![image](https://user-images.githubusercontent.com/76638444/122409797-6d6b9600-cf51-11eb-93c7-ae64d19cb134.png)
After:
```
.lobby__counters {
    position: relative !important;
    order: 1 !important;
    align-items: center !important;
    justify-content: center !important;
    width: 100% !important;
}
```
![image](https://user-images.githubusercontent.com/76638444/122409933-870cdd80-cf51-11eb-8b2f-3ee8c3599d78.png)

**Comment by noahsemus** [comment]
Fixed by reducing the font size in vw rather than stacking. Should appear in the next update.
