### ISSUE TITLE
Variants table overflows on homepage

### ISSUE THREAD

**Issue by LudamStudio** [prettierlichess/prettierlichess#58]
![image](https://user-images.githubusercontent.com/71848144/122623770-02aa7f80-d063-11eb-9b77-1cc316b08956.png)
Looks like the color of the premove indicator color. It is now the same as the color before the premove. 
This did not happen before, the color of the premove indicator color was the same as the move indicator colorr. 
This ruins themes like the one on chess.com. I hope you can fix it soon
![image](https://user-images.githubusercontent.com/71848144/122623918-9aa86900-d063-11eb-8127-d85447d1eef6.png)
This also happens, the variants and the mode (friendly or points) are not seen
Thanks for your attention. And congratulations on doing Streamer mode, I fit you very well.

**Comment by noahsemus** [comment]
For the premove indicator color this is intended as to closer match what vanilla lichess does. Will look into the variants table being hidden!

**Comment by LudamStudio** [comment]
I get it, but as I said, it ruins many of the themes as the color changes. I hope you can leave it as it was before

**Comment by noahsemus** [comment]
Variant table overflow now to be fixed in the next update!
