### ISSUE TITLE
Resizing lobby/quick pairing.

### ISSUE THREAD

**Issue by ToTheMoon1234** [prettierlichess/prettierlichess#60]
Hello,
It would be awesome if is is possible to make the quick pairing/lobby menu bigger, the issues currently are 

1. I use the graph method of display in the lobby menu, unfortunately a part of it is not visible due to the small size( see the image attached)(the three challenges just beyond 30 are not visible properly, two of them not being differentiable as they are on each other). A bigger lobby would make it easier to view available games.
2. My interest is to play games and look for games in the lobby when I open up the site and it is kind of irritating seeing such a big Lichess TV, which I don't use frequently, instead of the lobby. A bigger lobby would make it easier to see all games at once instead of all games being a bit cramped together.
![image](https://user-images.githubusercontent.com/73231423/123302151-085c0580-d53a-11eb-9dc9-85794a3a5d51.png)

I hope this gets fixed and I would like to drop a few suggestions (of course you would know better what to do)
1: Swap the Lichess TV menu with the Lobby/quick pairing menu or better if you give an option to user how they to keep them.
2: Make the blocks adjustable in size or find a balance between Lobby and TV( I would love to see Lobby in middle instead of TV)

Thanks for this wonderful extension, it truly makes Lichess more enjoyable than ever. :-)

Just another small request: Can the "play with the computer" be placed bit towards top please, it is wayy down at the bottom.
![image](https://user-images.githubusercontent.com/73231423/123304800-fe87d180-d53c-11eb-8e84-a6bb736ef0ce.png)

**Comment by noahsemus** [comment]
Thanks for the issue! In terms of changing the homepage layout we don't have any plans to change it -- the choice of where things are placed are very much intentional and made to cater to an audience that not only plays chess on the site, but also watch and explore chess on the rest of the site as well.

As for the graph we'll definitely look into supporting this!

**Comment by noahsemus** [comment]
Graph is now fixed in the next update!
