### ISSUE TITLE
The API Reference is still somewhat difficult to read

### ISSUE THREAD

**Issue by LandonSchropp** [prettierlichess/prettierlichess#62]
I saw that there was a previous issue (#38) about the API reference, but I'm still seeing some styling issues:

<img width="927" alt="Screen Shot 2021-07-10 at 3 07 35 PM" src="https://user-images.githubusercontent.com/361591/125175264-cd83df80-e17f-11eb-81f8-d37f0c8b874f.png">

Thanks!

**Comment by TheTrio** [comment]
Yes, it doesn't seem to be working. The only thing I can think of is that Lichess changed the html classes on their end. I don't know if this is something they do often.

**Comment by TheTrio** [comment]
That is odd. The styles.css is being loaded on that page. 
![image](https://user-images.githubusercontent.com/10794178/125472956-e43baa8f-d19b-4846-8ed5-b79e0b6ac528.png)

**Comment by noahsemus** [comment]
Found the problem. On the url it should read `["*://lichess.org/api*"]`, rather than `["*://lichess.org/api/*"]`. Firefox seemed to need this whereas Chrome did not. Will be fixed with the next update.

**Comment by TheTrio** [comment]
Any ideas on styling this page though? I for one can't think of any. It looks as if the class names change frequently.

**Comment by noahsemus** [comment]
I think it's better to leave unstyled. It isn't really a part of the core lichess experience for the typical end-user, so there's no big incentive to style it.

**Comment by LandonSchropp** [comment]
Thanks for digging in here and tackling this!
