### ISSUE TITLE
no evaluation gauge at 110% zoom

### ISSUE THREAD

**Issue by Rishabh672003** [prettierlichess/prettierlichess#63]
![Image 229](https://user-images.githubusercontent.com/53911515/125296818-4b90e380-e344-11eb-9e7b-1ff567e9ea36.png)

**Comment by Rishabh672003** [comment]
![Image 230](https://user-images.githubusercontent.com/53911515/125395382-c00d6600-e3c8-11eb-84e5-8b745c3860e9.png)

this is also a bug in player names

**Comment by noahsemus** [comment]
Both of these should be fixed in the next update!
