### ISSUE TITLE
create game button missing from lobby

### ISSUE THREAD

**Issue by zbrasseaux** [prettierlichess/prettierlichess#64]
there is no button to create a game at the bottom on the lobby. In vanilla lichess, the button is always off to the side.
<img width="407" alt="Screen Shot 2021-07-15 at 12 25 34 PM" src="https://user-images.githubusercontent.com/22946524/125831079-fdf9437e-c8c4-4c59-b587-22e3eeb2ad4c.png">
As you can see in the above image, there is no button at the bottom of the list of games
<img width="407" alt="Screen Shot 2021-07-15 at 12 25 40 PM" src="https://user-images.githubusercontent.com/22946524/125831091-225cc186-1797-4ca1-9647-2ab52c606f9b.png">
In the correspondence tab, however, you can in fact see the button. This shows that it does exist, but it cannot be seen in the lobby tab

**Comment by TheTrio** [comment]
The buttons you're referring to are on the bottom of the page(instead off to the size as is on vanilla lichess)

![image](https://user-images.githubusercontent.com/10794178/125846780-27b7aacf-0b96-4125-be94-80b6a315e764.png)
