### ISSUE TITLE
Port extension to Microsoft Edge

### ISSUE THREAD

**Issue by bastiantangedal** [prettierlichess/prettierlichess#65]
As the title says, could this extension be supported on Microsoft Edge as well? I'm happy to do it myself if that is of interest.
[This page explains how this can be done.](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension)

**Comment by noahsemus** [comment]
As of right now, we have no plans to port it, but feel free to create a PR and do it!

**Comment by bastiantangedal** [comment]
After further investigation, I've concluded that porting the extension itself is pretty easy, but the whole process of publishing it is something I think the owner of the extension should do. 

Sideloading the extension worked perfect, so in theory, porting the extension to Microsoft Edge is 0% work in terms of changing source code. :shipit:

**Comment by Jayfeather24** [comment]
@bastiantangedal You could download the source code, and then turn on developer mode in edge://extensions, and then load unpacked. It works perfectly as edge runs on chromium as well.

**Comment by Dboingue** [comment]
I thought web extensions that worked in chrome would also work in Edge for the same reason as previous comment.  I guess there are "store" issues.  Another delaying layer.

**Comment by bastiantangedal** [comment]
For anyone new coming to this issue, I ended up just sideloading the extension myself. It is easy, fast & works great. 

[Here is how I did it](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/getting-started/extension-sideloading)
