### ISSUE TITLE
Startpage is not responsive anymore

### ISSUE THREAD

**Issue by Jannik66** [prettierlichess/prettierlichess#7]
If I shrink my browser window the lichess.org startpage gets...
![image](https://user-images.githubusercontent.com/36984337/109402622-93940880-7957-11eb-89bd-0627a8e9643a.png)

Btw I love this project & the style. Please keep up the great work!! I really appreciate it! <3

**Comment by noahsemus** [comment]
Yes, responsiveness is not yet supported. This is definitely in the road map though, so stay tuned!

**Comment by Jannik66** [comment]
Nice! I also spotted that the sidenav doesn't work, I think this also belongs to the "responsive" issue.
![sidenav](https://user-images.githubusercontent.com/36984337/109509603-576cbf00-7aa1-11eb-98dc-4d829109cf9c.gif)

**Comment by noahsemus** [comment]
Yes for sure. Actually just fixed this last night, so fix for this and responsiveness incoming!

**Comment by Jannik66** [comment]
Thank you! Awesome <3
