### ISSUE TITLE
Firefox extension link ?

### ISSUE THREAD

**Issue by Ellipse0934** [prettierlichess/prettierlichess#70]
The link for the firefox addon: https://addons.mozilla.org/en-US/firefox/addon/prettier-lichess/ leads to a 404
![image](https://user-images.githubusercontent.com/7466364/136660541-59b4c6ed-fc57-43e6-be7f-f5874ada18e8.png)

**Comment by pabuisson** [comment]
Hey @noahsemus 👋 I could try and give it a try, I've been developping a browser addon for a few years now, with webpack as a build tool. However this will impact the structure of all the extension & dev workflow, since for now there's no building involved. 

Would you be okay with this?

**Comment by noahsemus** [comment]
Please feel free to open up a branch and give it a go!

**Comment by noahsemus** [comment]
Please feel free to open up a branch and give it a go!

**Comment by pabuisson** [comment]
Alright. I think I have something working. I'll clean up, document a bit, and open a PR 👍

**Comment by pabuisson** [comment]
I've submitted a PR here: https://github.com/prettierlichess/prettierlichess/pull/76
Tried to keep it as basic as possible (webpack config can quickly be overwhelming)

**Comment by noahsemus** [comment]
We are now in the process to get reuploaded to the FF add on store. Big thanks to @pabuisson and hopefully we will see it back up soon!

**Comment by noahsemus** [comment]
We are now back up on Firefox!
