### ISSUE TITLE
Clock is displaying near the board, but it shouldn't

### ISSUE THREAD

**Issue by janneslessmann** [prettierlichess/prettierlichess#72]
As you can see the clock is displaying near the board.
I already played on Lichess a few hours before where the clock was displaying on the right side as usual (where the notation also is). I didn't change any Lichess settings, nor did I change anything in the extension itself.
_The clock is also displaying correctly on the right side, when I disable the extension but then near the board again when I re-enable it._
![lichess](https://user-images.githubusercontent.com/88435053/140582613-b8e2f898-1b6c-4b45-85f2-33a8820f4e9e.png)

**Comment by noahsemus** [comment]
This is Prettier's "vertical layout" option. If you scroll down to the bottom right of the page there will be a subtle button to turn this on or off.
