### ISSUE TITLE
Board gets tinier than normal on the plugin and cannot be restored to regular size. 

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [prettierlichess/prettierlichess#73]
![prettierlichess](https://user-images.githubusercontent.com/76933354/141465105-0f3e7f5e-4613-4652-9ab3-e5c014d0b599.png)
![regularlichess](https://user-images.githubusercontent.com/76933354/141465122-52862293-fa26-48c4-a9bb-0a0e4b6742bf.png)

All the settings including the browser zoom level is the same ( 100% ). The board doesn't get any larger on the plugin than the size in the picture. Any solution? And why does this happen?

**Comment by noahsemus** [comment]
This is the intended size for the board and a byproduct of how we affect the layout.
