### ISSUE TITLE
Cursor position detection is bugged, resizing the browser window fixes the problem temporarily

### ISSUE THREAD

**Issue by crafty35a** [prettierlichess/prettierlichess#77]
Similar to #17 and #33, except the issue for me is vertical, not horizontal.

This just started happening to me recently - when I start a game, the mouse cursor seems bugged. The click is registered maybe a half square lower than where I see it, causing me to pick the wrong piece often. To fix it, I have been resizing the browser window, then maximizing it again, and it's resolved. But it comes back with every game. Turning off Prettier Lichess also fixes the issue.

**Comment by noahsemus** [comment]
Will be looking into this in the coming week.

**Comment by noahsemus** [comment]
This should now be fixed with today's update.
