### ISSUE TITLE
No "streamer mode" button

### ISSUE THREAD

**Issue by Bizarrebra** [prettierlichess/prettierlichess#79]
Hello guys! In this last release 3.3.3 I can't find the streamer vertical mode. Is that an issue? Has it been removed or moved to another place? Any pointer would be highly appreciated since that's the layout I use for my streams and now it's gone. Thanks!

![noStreamerButton](https://user-images.githubusercontent.com/83036427/145062745-a50aaba7-4981-4b1e-bead-7d7df7d86ddf.png)

**Comment by noahsemus** [comment]
Hi there, sorry for the late response! The vertical layout button should still be in the bottom right, which is odd. Are you on chrome or firefox?

**Comment by Bizarrebra** [comment]
Hi. I'm on Chrome. The funny thing is that when I use it on Chrome on my Mac, I can see the button, but that might be because the Mac and Windows version have different coding, I presume. Anyway, I thought that the button might be hidden somewhere, but even a search by "vertical" threw 0 results. The button is simply not there in the latest version 3.3.3. My Chrome (on PC) is up-to-date, by the way. Thanks!

**Comment by noahsemus** [comment]
We cannot seem to recreate this bug. Maybe try uninstalling and reinstalling the extension, but we are unfortunately scratching our heads on this one.

**Comment by Bizarrebra** [comment]
Hello. I've tried removing it from Chrome and resinstalling a couple of times, and the button is still not there. I've also imported a config where I use to have the vertical streamer mode, but I don't think that is saved in the JSON config file. Anyway, that didn't help either. I've tried performed a search for "vertical" and "streamer" and there's nothing on the game page. It's just not there. I'm not sure if any other extension or some sort of firewall/antivirus config might be blocking the CSS? It's weird but I can't think of anyhting else if it works for you. Is there any sort of log or anything I can get for you in order to troubleshoot this?

**Comment by Bizarrebra** [comment]
[SOLVED] OK, I found the problem. I'll post the solution here in case other folks are having the same thing. Since you guys weren't able to reproduce the issue and everything seems up-to-date I started suspecting about my antivirus: Kaspersky Internet Security. A quick search threw some interesting results, apparently Kaspersky injects some Javascrtipt code by default in all pages and some of them work erratically. This all sounded familiar. I disabled the option to inject by default that code and voilà!, the button appeared again. In you're in the same situation, that setting is in the "Network settings", down in the "Traffic processing" section, just uncked the case "Inject script into web traffic to interact with web pages", which is checked by default. Hope this can help anyone. Thanks guys! You can close this issue.

**Comment by noahsemus** [comment]
Awesome, glad this is resolved!
