### ISSUE TITLE
Style issues

### ISSUE THREAD

**Issue by dav1312** [prettierlichess/prettierlichess#80]
Style issues when replaying puzzles

![image](https://user-images.githubusercontent.com/63931154/145425865-92c12be3-78c1-492e-a415-f267cc4d430b.png)
---
Color not applied to active or focused links

![image](https://user-images.githubusercontent.com/63931154/145454384-ade2ffce-ac7d-41f0-ad51-85f1f94c752a.png)
---
Color not applied to votes in puzzles

![image](https://user-images.githubusercontent.com/63931154/145454504-742d4b64-3f69-48f9-ba51-eb10fc2f0704.png)

**Comment by noahsemus** [comment]
Will look into this, thank you!
