### ISSUE TITLE
Cannot customize anything

### ISSUE THREAD

**Issue by JJB-e** [prettierlichess/prettierlichess#82]
The extension changes the look of Lichess, but I cannot customize anything. Also, when I click on "Board Colors", "Import Profile", "Export Profile", nothing happens.
![bug](https://user-images.githubusercontent.com/96786964/147585215-fabf8f59-fbe6-4136-8ee8-4d493d46ddae.JPG)

**Comment by TheTrio** [comment]
Looks like the extension is missing some files 

![image](https://user-images.githubusercontent.com/10794178/147595645-f9a37356-07a5-413a-bb71-c277ba2955f3.png)

When loading the unpacked extension through `npm run build` though all files are present 

![image](https://user-images.githubusercontent.com/10794178/147595780-090aeaea-85f9-4c65-87c0-2ab705bd6808.png)

Also, can't replicate this issue on firefox. Probably the chrome web store version has some files missing

**Comment by noahsemus** [comment]
@TheTrio thanks for this! Yes, I am also getting problems with the latest version on chrome. Must've screwed something up when uploading. I will upload a newer version now and hopefully that should rectify this.

**Comment by noahsemus** [comment]
This issue should be resolved with the most recent update.
