### ISSUE TITLE
Move highlights

### ISSUE THREAD

**Issue by ChuckDimeCliff** [prettierlichess/prettierlichess#84]
Options to design the move highlights would be awesome.
Personally, I would like the following:

1. When using the two-click move method, the square you are about to move to gets highlighted. I would also like this for click and drag.
2. When capturing a piece, I would like the piece to be either circled (like the right click highlight options) or the whole square highlighted, instead of the four triangles in the corners.

**Comment by noahsemus** [comment]
We don't currently have any plans to change the move highlight designs past color switching. Sorry!
