### ISSUE TITLE
Chrome extension: Color change is not displayed in the extension

### ISSUE THREAD

**Issue by Jannik66** [prettierlichess/prettierlichess#9]
When I change a color in the extension, the default color is displayed after closing & reopening.
It should still show the color I've configured before.

![extension](https://user-images.githubusercontent.com/36984337/109517638-c4845280-7aa9-11eb-9de7-2180bf2e479e.gif)

**Comment by Durush** [comment]
Hey @Jannik66 This defect was introduced accidentally with version 0.1.0 and was immediately patched. unfortunately the chrome webstore often takes over 24 hours to approve even trivial changes. I'm hoping you should be able to see this functionality working properly sometime today or tomorrow. Thanks so much for the feedback and for helping us to improve the extension!

**Comment by Jannik66** [comment]
Ah there we go. It's fixed for me :)
