### ISSUE TITLE
Unable to copy text from inbox messages

### ISSUE THREAD

**Issue by crafty35a** [prettierlichess/prettierlichess#91]
With Prettier Lichess enabled, I am unable to select/copy text from messages in my inbox.

**Comment by MatthewMaginniss** [comment]
I noticed this a few days ago too. You are also unable to copy the PGN of a match from the analysis tab. It will completely highlight it on click but you cant copy it. I have been going into inspect elements and copying from there. 

I've been trying to figure out what could be causing this but I've not figured it out either. Doing a bit of digging now. If I figure it out, I'll make a PR.

**Comment by TheTrio** [comment]
Its probably as simple as setting `user:select: text` on the elements you want selected. Haven't tried it but that should work.

**Comment by crafty35a** [comment]
I checked the code, Prettier is making the entire site unselectable by specifying "user-select: none;" on the root element - see styles.css:
https://github.com/prettierlichess/prettierlichess/blob/2e792bca4d81219ead74fa41a72a00f140d98a77/src/styles.css#L65

I'm not sure if there's some reason it's being done this way. Likely the better idea would be for Prettier to specify certain elements as unselectable. If it remains as is, we would have to go in and override the style every single element that we want to be selectable.

**Comment by crafty35a** [comment]
Here's the commit that made the change, maybe @noahsemus can let us know if there's a reason root is being specified as unselectable - it would be easier to revert that than to try and manually fix everything we want selectable.

**Comment by MatthewMaginniss** [comment]
Unclear to me what the goal was. The commit says styled broadcast and fixed mobile bugs. If the issue was a mobile thing like I am kind of expecting, maybe setting the user-select to none only for screen of a certain size or smaller might be the way to go and then leave it as is for desktops. I cannot find any issues that arise from having this rule removed on the desktop browsers

**Comment by noahsemus** [comment]
Sorry about this -- have been very busy and finding little time to keep the extension updated. Yes, this was done for mobile and was a complete oversight. Thanks for the diligent work everyone! Will try to push an update the store with this fix today.

**Comment by noahsemus** [comment]
Should now be fixed with the latest update
