### ISSUE TITLE
Create a game/Play with the computer/ Play with a friend are impossible to use now

### ISSUE THREAD

**Issue by TiltedAngle** [prettierlichess/prettierlichess#93]
Hey

I've been using prettierlichess for a while now but have never come across this issue until today. I haven't installed anything other than prettierlichess. I cannot create a game/play w/ a computer/play with a friend as it doesn't pop up across the entire screen, it only pops up through the corner. Any ideas how to fix this?
<img width="1416" alt="Screenshot 2022-04-26 at 10 33 53" src="https://user-images.githubusercontent.com/83716443/165246591-c365cda6-fd66-4f1e-9280-fa8372de6e9a.png">
?

**Comment by janneslessmann** [comment]
I have the same ![problem](https://user-images.githubusercontent.com/88435053/165359483-1fe30975-74ec-497c-ac29-57296db4fd6c.PNG)
