### ISSUE TITLE
Game setup window misplaced and obscured by leaderboard

### ISSUE THREAD

**Issue by TheHypnotist333** [prettierlichess/prettierlichess#96]
When I go to start a game with anyone the setup window pops up on the left side of the screen and is partially covered by the leaderboard on the home screen. It makes it impossible to start a game with anyone
![game control blocked by leaderboard](https://user-images.githubusercontent.com/104811236/166401562-0508acbe-cc2f-4e13-91b7-e1f0fec58333.JPG)
.

**Comment by janneslessmann** [comment]
> Should be fixed with #95

It isn't fixed for me yet. (using latest version)

**Comment by TheTrio** [comment]
I don't know if the extension's been updated on the store. @noahsemus might know more about that.

**Comment by noahsemus** [comment]
It it updated on the store and fixed on my end. Are you using Firefox or
Chrome?

**Comment by janneslessmann** [comment]
It is fixed for me now. Probably took a while for it to be updated(?)
Thanks!

**Comment by TheHypnotist333** [comment]
It works for me now thanks

**Comment by janneslessmann** [comment]
This issue can be closed, since it works for the issuer now, right?
