### ISSUE TITLE
User Styles / Prettier Lichess for phone browsers

### ISSUE THREAD

**Issue by Pawnstreetblues** [prettierlichess/prettierlichess#99]
Hello,

I use the lichess site with my iPhone and I can’t get stylus or prettier lichess.  Could you make themes available for the phone browser community?  It’s my dream to play on a theme like this:
![4BFB69F2-784F-4354-A138-7B5BC3A4ECEE](https://user-images.githubusercontent.com/106215734/170168521-76f6ff70-39ec-4acd-baac-e4156545e52e.jpeg)

**Comment by janneslessmann** [comment]
_As far as I know there is no possibility to use add-ons in regular browser on your phone._
But there is a browser called "Kiwi" which has exactly this feature.

**Comment by noahsemus** [comment]
Yes, the extension does have an entire mobile breakpoint that can be used on iOS or Android as long as you have a browser that supports extensions. I've tested it on Kiwi and Firefox and both work. Unfortunately chrome doesn't support extensions on mobile.
